### ISSUE TITLE
[bug] QR Code doesn't show up when connecting with Wallet Connect

### ISSUE THREAD

**Issue by thi-investax** [reown-com/appkit#1759]
### Summary

Hi everyone. 
Im trying to setup web3react modal with wagmi/viem. Every wallet works fine except wallet connect. When I click on wallet connect, it doesn't show me any thing, no QR code shown.

It gave me this error 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'wallet')
    at new W3mConnectingWcView (index.js:16:23)
    at TemplateInstance._clone (lit-html.js:674:1)
    at ChildPart._commitTemplateResult (lit-html.js:979:1)
    at ChildPart._$setValue (lit-html.js:835:1)
    at TemplateInstance._update (lit-html.js:727:1)
    at ChildPart._commitTemplateResult (lit-html.js:975:1)
    at ChildPart._$setValue (lit-html.js:835:1)
    at render (lit-html.js:1441:1)
    at W3mRouter.update (lit-element.js:122:34)
    at W3mRouter.performUpdate (reactive-element.js:854:1)
```

![image](https://github.com/WalletConnect/web3modal/assets/118243127/bd1b7c81-b990-49e9-98ad-df99afe7972b)

Extra information:
Package.json

```json
  "dependencies": {
    "@date-io/date-fns": "^1.3.13",
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@fullstory/browser": "^1.4.5",
    "@hookform/error-message": "^0.0.4",
    "@hookform/resolvers": "^0.1.0",
    "@hookform/strictly-typed": "0.0.3",
    "@mui/icons-material": "^5.3.1",
    "@mui/lab": "^5.0.0-alpha.66",
    "@mui/material": "^5.3.1",
    "@mui/styles": "^5.3.0",
    "@sentry/react": "^5.26.0",
    "@sentry/tracing": "^5.26.0",
    "@web3-react/core": "^6.0.9",
    "@web3-react/injected-connector": "^6.0.7",
    "@web3-react/walletlink-connector": "^6.2.14",
    "@web3modal/wagmi": "^3.5.6",
    "add": "^2.0.6",
    "axios": "^0.21.2",
    "draftjs-to-html": "^0.9.1",
    "ethers": "^5.6.2",
    "kaktana-react-lightweight-charts": "^2.0.0",
    "lodash": "^4.17.21",
    "material-ui-phone-number": "^3.0.0",
    "material-ui-popup-state": "^1.6.1",
    "mobx": "^5.15.4",
    "mobx-react": "^6.2.2",
    "mui-rte": "^2.0.1",
    "process": "^0.11.10",
    "pure-react-carousel": "^1.27.6",
    "react": "^17.0.2",
    "react-device-detect": "^2.1.2",
    "react-dom": "^17.0.2",
    "react-dropzone": "^11.2.4",
    "react-error-boundary": "^3.0.2",
    "react-google-charts": "^3.0.15",
    "react-gtm-module": "^2.0.11",
    "react-hook-form": "6.14.1",
    "react-idle-timer": "^4.6.4",
    "react-multi-email": "0.5.3",
    "react-number-format": "^4.4.1",
    "react-otp-input": "^2.3.0",
    "react-player": "^2.9.0",
    "react-query": "^2.26.2",
    "react-responsive-carousel": "^3.2.20",
    "react-router-dom": "^5.3.0",
    "react-scroll": "^1.8.1",
    "viem": "1.21.4",
    "wagmi": "1.4.13",
    "web3": "^1.4.0"
  },

```

My code setup:

```js
import React from 'react'
import ReactDOM from 'react-dom'
import 'svgxuse'
import AdapterDateFns from '@mui/lab/AdapterDateFns'
import LocalizationProvider from '@mui/lab/LocalizationProvider'
import { CssBaseline } from '@mui/material'
import { StyledEngineProvider, ThemeProvider } from '@mui/material/styles'
import createGenerateClassName from '@mui/styles/createGenerateClassName'
import StylesProvider from '@mui/styles/StylesProvider'
import { AppStateProvider } from 'app/hooks/useAppState'
import { AppThemeProvider } from 'AppThemeProvider'
import { UserProvider } from 'auth/context'
import { Toast } from 'components/Toast'
import { ToastContainer } from 'components/ToastContainer/ToastContainer'
import { history } from 'config/history'
import { EntryPoint } from 'EntryPoint'
import { QueryCache, ReactQueryCacheProvider } from 'react-query'
import { Router, Switch } from 'react-router-dom'
import { ToastProvider } from 'react-toast-notifications'
import { setupFullStory } from 'setupFullStory'
import { setupGtagManager } from 'setupGtagManager'
import { setupSentry } from 'setupSentry'
import { createWeb3ReactRoot, Web3ReactProvider } from '@web3-react/core'
import { NetworkContextName } from 'config/blockchain/constants'
import getLibrary from 'config/blockchain/getLibrary'
import { createWeb3Modal, defaultWagmiConfig } from '@web3modal/wagmi/react'

import { WagmiConfig } from 'wagmi'
import { arbitrum, mainnet } from 'viem/chains'
import { RouterController } from '@web3modal/core'

// 1. Get projectId at https://cloud.walletconnect.com
const projectId = 'I already set it'

// 2. Create wagmiConfig
const metadata = {
  name: 'Web3Modal',
  description: 'Web3Modal Example',
  url: 'https://web3modal.com',
  icons: ['https://avatars.githubusercontent.com/u/37784886']
}

const chains = [mainnet, arbitrum]
const wagmiConfig = defaultWagmiConfig({ chains, projectId, metadata })
const queryCache = new QueryCache({
  defaultConfig: {
    queries: {
      refetchOnWindowFocus: false
    }
  }
})

createWeb3Modal({
  wagmiConfig,
  projectId,
  chains,
  themeMode: 'dark',
  themeVariables: {
    '--w3m-color-mix': '#00DCFF',
    '--w3m-color-mix-strength': 20
  }
})
const Web3ProviderNetwork = createWeb3ReactRoot(NetworkContextName)

const generateClassName = createGenerateClassName({
  productionPrefix: 'ix'
})

setupSentry()
setupFullStory()
setupGtagManager()

const IXApp = () => {
  return (
    <WagmiConfig config={wagmiConfig}>
      <LocalizationProvider dateAdapter={AdapterDateFns}>
        <StylesProvider generateClassName={generateClassName}>
          <AppThemeProvider>
            {theme => (
              <StyledEngineProvider injectFirst>
                <ThemeProvider theme={theme}>
                  <ReactQueryCacheProvider queryCache={queryCache}>
                    <CssBaseline />
                    <UserProvider>
                      <Router history={history}>
                        <Web3ReactProvider getLibrary={getLibrary}>
                          <Web3ProviderNetwork getLibrary={getLibrary}>
                            <AppStateProvider>
                              <Switch>
                                <ToastProvider
                                  components={{ Toast, ToastContainer }}
                                  autoDismiss={false}
                                  placement='bottom-right'
                                >
                                  <EntryPoint />
                                </ToastProvider>
                              </Switch>
                            </AppStateProvider>
                          </Web3ProviderNetwork>
                        </Web3ReactProvider>
                      </Router>
                    </UserProvider>
                  </ReactQueryCacheProvider>
                </ThemeProvider>
              </StyledEngineProvider>
            )}
          </AppThemeProvider>
        </StylesProvider>
      </LocalizationProvider>
    </WagmiConfig>
  )
}

ReactDOM.render(<IXApp />, document.getElementById('root'))

```

I really appreciate any helps. Thank you!

### List of related npm package versions

"@web3modal/wagmi": "^3.5.6",
  "viem": "1.21.4",
    "wagmi": "1.4.13"
    
    We still have some legacy web3 packages so im not sure if this might conflict with web3modal's packages.
      "@web3-react/core": "^6.0.9",
    "@web3-react/injected-connector": "^6.0.7",
    "@web3-react/walletlink-connector": "^6.2.14",
        "ethers": "^5.6.2",

**Comment by glitch-txs** [comment]
Hi, could you share your devDeps

**Comment by thi-investax** [comment]
hi @glitch-txs 
Here are my devDeps , thanks
```json
  "devDependencies": {
    "@babel/cli": "^7.13.10",
    "@babel/core": "^7.13.10",
    "@babel/plugin-proposal-class-properties": "^7.16.7",
    "@babel/plugin-proposal-decorators": "^7.16.7",
    "@babel/plugin-transform-runtime": "^7.16.7",
    "@babel/preset-env": "^7.13.10",
    "@babel/preset-react": "^7.12.10",
    "@babel/preset-typescript": "^7.15.0",
    "@babel/runtime": "^7.13.10",
    "@fullstory/babel-plugin-annotate-react": "^2.0.1",
    "@playwright/test": "^1.21.0",
    "@storybook/addon-actions": "^6.4.14",
    "@storybook/addon-essentials": "^6.4.14",
    "@storybook/addon-links": "^6.4.14",
    "@storybook/builder-webpack5": "^6.4.14",
    "@storybook/manager-webpack5": "^6.4.14",
    "@storybook/node-logger": "^6.4.14",
    "@storybook/preset-create-react-app": "^4.0.0",
    "@storybook/react": "^6.4.14",
    "@svgr/webpack": "^6.1.2",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/react-hooks": "^3.4.1",
    "@testing-library/user-event": "^12.1.10",
    "@typechain/ethers-v5": "^10.0.0",
    "@types/axios": "^0.14.0",
    "@types/classnames": "^2.2.10",
    "@types/dompurify": "^2.2.3",
    "@types/draftjs-to-html": "^0.8.0",
    "@types/flat": "^5.0.1",
    "@types/lodash": "^4.14.156",
    "@types/material-ui-phone-number": "^2.2.1",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-gtm-module": "^2.0.1",
    "@types/react-otp-input": "^2.0.0",
    "@types/react-router": "^4.3.1",
    "@types/react-router-dom": "^5.3.2",
    "@types/react-scroll": "^1.8.2",
    "@types/react-time-picker": "^4.0.2",
    "@types/react-toast-notifications": "^2.4.0",
    "@types/react-window": "^1.8.2",
    "@types/socket.io-client": "^1.4.33",
    "@types/tinycolor2": "^1.4.2",
    "@types/yup": "^0.29.4",
    "@typescript-eslint/eslint-plugin": "^5.8.1",
    "@typescript-eslint/parser": "^5.8.1",
    "allure-playwright": "^2.0.0-beta.14",
    "axios-mock-adapter": "^1.20.0",
    "babel-eslint": "^10.1.0",
    "babel-plugin-import": "^1.13.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "concurrently": "^6.4.0",
    "copy-webpack-plugin": "^10.2.0",
    "css-loader": "^6.5.1",
    "dotenv": "^10.0.0",
    "eslint": "^8.12.0",
    "eslint-config-prettier": "^6.12.0",
    "eslint-config-react-app": "^6.0.0",
    "eslint-config-standard-with-typescript": "^18.0.2",
    "eslint-plugin-flowtype": "^8.0.3",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-standard": "^4.0.1",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.5.0",
    "husky": "^4.2.5",
    "jest": "24.9.0",
    "jest-environment-jsdom-sixteen": "^1.0.3",
    "jest-localstorage-mock": "^2.4.3",
    "jest-sonar-reporter": "^2.0.0",
    "lint-staged": "^10.5.4",
    "playwright": "^1.21.0",
    "prettier": "^2.1.2",
    "react-query-devtools": "^2.6.0",
    "react-test-renderer": "^16.13.1",
    "rimraf": "^3.0.2",
    "standard": "^14.3.4",
    "storybook-dark-mode": "^1.0.9",
    "style-loader": "^3.3.1",
    "ts-loader": "^9.2.6",
    "typechain": "^8.0.0",
    "url-loader": "^4.1.1",
    "wait-on": "^6.0.0",
    "webpack": "^5.65.0",
    "webpack-bundle-analyzer": "^4.5.0",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.7.2"
  },
  "resolutions": {
    "babel-loader": "8.1.0"
  },

```

**Comment by glitch-txs** [comment]
Could you update webpack to 5.71 and try again?

**Comment by thi-investax** [comment]
![image](https://github.com/WalletConnect/web3modal/assets/118243127/2a915693-d5e0-4301-bfbb-935e4766daf6)
oh it works now after upgrading webpack. Thank you a lot @glitch-txs 🙏🙏🙏

**Comment by glitch-txs** [comment]
Awesome 🙌
