### ISSUE TITLE
[bug] connector.getProvider is not a function (Angular)

### ISSUE THREAD

**Issue by vanyasav** [reown-com/appkit#3103]
### Link to minimal reproducible example

https://github.com/vanyasav/angular-reown-wagmi

### Summary

Error appears on the console when disconnecting from wallet or rejecting to connect to a wallet

```
chunk-WME3VOFU.js?v=c5e50c67:93 ERROR TypeError: connector.getProvider is not a function
    at WagmiAdapter.<anonymous> (client.js:493:73)
    at Generator.next (<anonymous>)
    at chunk-WME3VOFU.js?v=c5e50c67:93:61
    at ZoneAwarePromise (zone.js:2702:25)
    at __async (chunk-WME3VOFU.js?v=c5e50c67:77:10)
    at WagmiAdapter.syncAccount (client.js:456:6)
    at onChange (client.js:415:14)
    at listener (middleware.mjs:227:11)
    at vanilla.mjs:9:37
    at Set.forEach (<anonymous>)
```

[Screencast from 16-10-2024 17:59:18.webm](https://github.com/user-attachments/assets/55b73cb0-783d-4763-afc8-235282d04495)

### List of related npm package versions

    "@reown/appkit": "^1.1.4",
    "@reown/appkit-adapter-wagmi": "^1.1.4",
    "viem": "^2.21.27",
    "wagmi": "^2.12.18",

**Comment by vanyasav** [comment]
@rtomas still an issue in 1.3.2

**Comment by hellohasan** [comment]
@vanyasav i am still facing this issue on 
"@reown/appkit": "^1.4.1",
 "@reown/appkit-adapter-wagmi": "^1.4.1",

**Comment by hellohasan** [comment]
> @vanyasav i am still facing this issue on "@reown/appkit": "^1.4.1", "@reown/appkit-adapter-wagmi": "^1.4.1",
I am getting this type of Error
![WhatsApp Image 2024-11-20 at 17 09 24](https://github.com/user-attachments/assets/646d5e29-1292-4e19-9aa3-068d76f07494)

**Comment by hellohasan** [comment]
> @vanyasav i am still facing this issue on "@reown/appkit": "^1.4.1", "@reown/appkit-adapter-wagmi": "^1.4.1",
I am getting this error
![image](https://github.com/user-attachments/assets/591ebea6-37d4-4fba-974e-f899ff6b9852)
